
package dziekanat;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Main", targetNamespace = "http://dziekanat/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Main {


    /**
     * 
     * @param arg0
     * @return
     *     returns dziekanat.Student
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudent", targetNamespace = "http://dziekanat/", className = "dziekanat.GetStudent")
    @ResponseWrapper(localName = "getStudentResponse", targetNamespace = "http://dziekanat/", className = "dziekanat.GetStudentResponse")
    public Student getStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hi", targetNamespace = "http://dziekanat/", className = "dziekanat.Hi")
    @ResponseWrapper(localName = "hiResponse", targetNamespace = "http://dziekanat/", className = "dziekanat.HiResponse")
    public String hi(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<dziekanat.Student>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudents", targetNamespace = "http://dziekanat/", className = "dziekanat.GetStudents")
    @ResponseWrapper(localName = "getStudentsResponse", targetNamespace = "http://dziekanat/", className = "dziekanat.GetStudentsResponse")
    public List<Student> getStudents();

}
